{
 "title": "Negocio - Crypto Exchange",
 "refresh": "5s",
 "panels": [
  {
   "title": "Precio BTC/USDT en vivo ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "crypto_precio_actual{par=\"BTCUSDT\"}",
     "legendFormat": "BTC/USDT"
    }
   ]
  },
  {
   "title": "Precio ETH/USDT en vivo ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "crypto_precio_actual{par=\"ETHUSDT\"}",
     "legendFormat": "ETH/USDT"
    }
   ]
  },
  {
   "title": "Variación 24h (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "crypto_variacion_24h_pct", "legendFormat": "{{par}}" }
   ]
  },
  {
   "title": "Mensajes publicados en Kafka",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(pipeline_mensajes_publicados_total[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Volumen 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "crypto_volumen_24h", "legendFormat": "{{par}}" }
   ]
  }
 ]
}